### PR TITLE
session_017_list_awards_of_students#70(issue): some fix of code for correct display list of awards- connected with api

### LINKED ISSUE #70: Jako opiekun chce mieć możliwość wyświetlania listy nagród podopiecznego.

### PR DESCRIPTION
**Pull request by miniMax18**

### CODE REVIEW

File: src/api/useAwards.ts [hunk 1]
```diff
@@ -15,19 +17,21 @@ type UseAwardsObjectDataResponse = {
...
-  fetch(...(args as [any])).then((res) => res.json());
+const fetcher = async (
+  url: string,
+): Promise<AxiosResponse<any>> =>
+  axiosInstance().get(url);
 
 const useAwards = (id: any): UseAwardsObjectDataResponse => {
-  const URL = process.env.VITE_REACT_APP_API_URL + ENDPOINT.prizesId.replace("{:id}", id)
-  const { data, error } = useSWR<GetPrizesByFetcher>(URL, fetcher);
+  //const URL = process.env.VITE_REACT_APP_API_URL + ENDPOINT.prizesId.replace("{:id}", id)
```
Comment (mniegrzybowska) [inline src/api/useAwards.ts]: delete comment

**Review by mniegrzybowska — APPROVED** [review]
good catch!

File: src/api/useAwards.ts (hunk 1 above)
Comment (miniMax18) [reply src/api/useAwards.ts]: done 👍
